pipeline {
    agent {
        docker {
            image 'eclipse-temurin:17-jdk'
        }
    }

    stages {
        stage('Hello World') {
            steps {
                sh '''
                    cat > HelloWorld.java <<'EOF'
public class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello World from Jenkins!");
    }
}
EOF

                    javac HelloWorld.java
                    java HelloWorld
                '''
            }
        }
    }
}
