pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
    stage('testing') {
      steps {
        echo '"hello world"'
      }
    }
    stage('Node Js Application installation') {
      steps {
        sh 'apt install nodejs'
      }
    }
    stage('npm installation') {
      steps {
        sh 'apt install npm'
      }
    }
  }
}
